//characters
export const GET_CHARACTERS_START = "GET_CHARACTERS_START";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";
export const PREV_PAGE_CHARACTER = "PREV_PAGE_CHARACTER";
export const NEXT_PAGE_CHARACTER = "NEXT_PAGE_CHARACTER";
export const JUMP_TO_PAGE_CHARACTER = "JUMP_TO_PAGE_CHARACTER";
export const GET_SINGLE_CHAR_START = "GET_SINGLE_CHAR_START";
export const GET_SINGLE_CHAR_SUCCESS = "GET_SINGLE_CHAR_SUCCESS";

//episodes
export const GET_EPISODES_START = "GET_EPISODES_START";
export const GET_EPISODES_SUCCESS = "GET_EPISODES_SUCCESS";
export const EPISODES_ERROR = "EPISODES_ERROR";
export const PREV_PAGE_EPISODE = "PREV_PAGE_EPISODE";
export const NEXT_PAGE_EPISODE = "NEXT_PAGE_EPISODE";
export const JUMP_TO_PAGE_EPISODE = "JUMP_TO_PAGE_EPISODE";

//locations
export const GET_LOCATIONS_START = "GET_LOCATION_START";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATION_SUCCESS";
export const LOCATIONS_ERROR = "LOCATIONS_ERROR";
export const PREV_PAGE_LOCATION = "PREV_PAGE_LOCATION";
export const NEXT_PAGE_LOCATION = "NEXT_PAGE_LOCATION";
export const JUMP_TO_PAGE_LOCATION = "JUMP_TO_PAGE_LOCATION";
