export const GET_CHARACTERS_START = "GET_CHARACTERS_START";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";
export const PREV_PAGE_CHARACTER = "PREV_PAGE_CHARACTER";
export const NEXT_PAGE_CHARACTER = "NEXT_PAGE_CHARACTER";
export const JUMP_TO_PAGE_CHARACTER = "JUMP_TO_PAGE_CHARACTER";

export const GET_EPISODES_START = "GET_EPISODES_START";
export const GET_EPISODES_SUCCESS = "GET_EPISODES_SUCCESS";
export const EPISODES_ERROR = "EPISODES_ERROR";
export const PREV_PAGE_EPISODE = "PREV_PAGE_EPISODE";
export const NEXT_PAGE_EPISODE = "NEXT_PAGE_EPISODE";
export const JUMP_TO_PAGE_EPISODE = "JUMP_TO_PAGE_EPISODE";
